name: safe_lodash
description: A modern Dart utility library delivering modularity, performance, & extras
version: 0.0.1
repository: https://github.com/pipihua666/safe_lodash

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
